
package com.soaps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalcularSalarioImplService", targetNamespace = "http://soaps.com/", wsdlLocation = "http://localhost:6060/soap/salario?wsdl")
public class CalcularSalarioImplService
    extends Service
{

    private final static URL CALCULARSALARIOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULARSALARIOIMPLSERVICE_EXCEPTION;
    private final static QName CALCULARSALARIOIMPLSERVICE_QNAME = new QName("http://soaps.com/", "CalcularSalarioImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6060/soap/salario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULARSALARIOIMPLSERVICE_WSDL_LOCATION = url;
        CALCULARSALARIOIMPLSERVICE_EXCEPTION = e;
    }

    public CalcularSalarioImplService() {
        super(__getWsdlLocation(), CALCULARSALARIOIMPLSERVICE_QNAME);
    }

    public CalcularSalarioImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULARSALARIOIMPLSERVICE_QNAME, features);
    }

    public CalcularSalarioImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULARSALARIOIMPLSERVICE_QNAME);
    }

    public CalcularSalarioImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULARSALARIOIMPLSERVICE_QNAME, features);
    }

    public CalcularSalarioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcularSalarioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalcularSalarioDao
     */
    @WebEndpoint(name = "CalcularSalarioImplPort")
    public CalcularSalarioDao getCalcularSalarioImplPort() {
        return super.getPort(new QName("http://soaps.com/", "CalcularSalarioImplPort"), CalcularSalarioDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcularSalarioDao
     */
    @WebEndpoint(name = "CalcularSalarioImplPort")
    public CalcularSalarioDao getCalcularSalarioImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaps.com/", "CalcularSalarioImplPort"), CalcularSalarioDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULARSALARIOIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULARSALARIOIMPLSERVICE_EXCEPTION;
        }
        return CALCULARSALARIOIMPLSERVICE_WSDL_LOCATION;
    }

}
